### ISSUE TITLE
Upgrade twig version

### ISSUE THREAD

**Issue by Davidmattei** [ems-project/EMSClientHelperBundle#143]
We are not able to use the twig spaceship operator, because we use twig version 2.10.

https://twig.symfony.com/doc/2.x/filters/sort.html

Spaceship supported added in 2.12:
https://github.com/twigphp/Twig/commit/f5950a5b1f6baf0d5410ca3067902f3a8cb64353

In composer.json
`"twig/twig" : "~2.10.0"`

Packagist: 
https://packagist.org/packages/twig/twig

**Comment by dameert** [comment]
Look through the issue and pr history we cannot simply update client helper because this would break many of our “frontend” templates due to macro implementation change

**Comment by Davidmattei** [comment]
Okay we need to investigate, but it's just going from 2.10 to 2.12 ?

**Comment by Davidmattei** [comment]
Okay, we need to fix this! First more information about why we didn't upgrade twig: https://github.com/twigphp/Twig/issues/3090

But now we just need to upgrade, on php 7.4 we have 1600+ deprecations logged because we use twig 2.10 for the clientHelperBundle.

https://github.com/twigphp/Twig/issues/3151

My suggestion, upgrade twig and Major Release preferably 3.4

**Comment by Davidmattei** [comment]
Tested on a current php 7.4 skeleton project and also older still 7.2 project. 
When we release the skeleton we should update twig/twig

**Comment by Davidmattei** [comment]
Wil be in 3.4 

https://github.com/ems-project/website-skeleton/issues/37
